### ISSUE TITLE
addon isn't loading when dropped in <Guild Wars 2>/addons

### ISSUE THREAD

**Issue by trini0n** [RaidcoreGG/GW2-Compass#1]
are there other dependencies that the compass relies on that i need to have installed? i'm currently using GW2 Addon Manager for my other addons and just dropped this one in the /addons folder, but I can't seem to get it to load. 

![image](https://github.com/RaidcoreGG/GW2-Compass/assets/24836973/d9bc1fad-6c44-455b-afcc-bb99c02673df)

**Comment by Sognus** [comment]
Hello,
loading Compass through Addon manager is not and will not be supported. Compass is a Nexus' addon - you can read more here [raidcore.gg/Nexus](https://raidcore.gg/Nexus). 

There is highly likely for other addons to be ported to Nexus as well in the future either by their authors or by raidcore/nexus team. 

Nexus is compatible with arcdps in following configuration:
- nexus: d3d11.dll
- addon loader: d3d11_chainload.dll 
- arcdps: put it's DLL into addons

Or most other combinations of above. Please take note that addon loader is NOT chainloading, therefore Nexus cannot be loaded by it.

**Comment by trini0n** [comment]
I see - I'm rather new to this but is there a link somewhere that walks you through how to chainload Nexus > AddOn Manager > ReShade

**Comment by DeltaRaidcore** [comment]
Get the Nexus Installer from the URL in Sognus' reply. The installer should automatically handle all of that.
In case it asks you to download .NET, you will have to do a manual installation of Nexus.

For a fully manual installation of Nexus + AddonLoader do the following:
1. Rename AddonLoader's `d3d11.dll` to `d3d11_chainload.dll` (.dll is the file extension, if it doesn't have one, leave it out)
2. Download Nexus' `d3d11.dll` and place it into the main directory of Guild Wars 2. https://api.raidcore.gg/d3d11.dll
3. You might have to unblock Nexus, to do this Right-Click -> Properties -> if there's an Unblock checkbox near Read-Only and Hidden, make sure it's checked.
4. (Optional) If using ArcDPS, move it into the addons directory to have it loaded by Nexus instead of Addon Loader.

**Comment by trini0n** [comment]
Thank you, your step-by-step worked perfectly 👍

**Comment by trini0n** [comment]
Another question - how do you edit the settings / position of the compass? I see a settings.json file that's in the Compass folder but all it says is

```
{
	"CompassIndicatorLong": null,
	"CompassIndicatorOutline": null,
	"CompassIndicatorTextPrefix": null,
	"CompassStripOffsetV": null,
	"IsCompassIndicatorLocked": null,
	"IsCompassIndicatorVisible": null,
	"IsCompassStripVisible": null,
	"IsCompassWorldVisible": null
}
```

**Comment by DeltaRaidcore** [comment]
You can access the options in Nexus by default via CTRL+O (O as in Options) or by clicking the Nexus icon in the top left and then selecting Options from the menu. There you should be able to set the values.

**Comment by DeltaRaidcore** [comment]
If you need further help I recommend you to ask via Discord https://discord.gg/raidcore. There I can give you some live support. :)
